"""create_competitor_domains_table

Revision ID: 15ef51c00a52
Revises: 534fb82c744e
Create Date: 2026-06-27 18:04:34.097757

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "15ef51c00a52"
down_revision: Union[str, Sequence[str], None] = "534fb82c744e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


domain_type_enum = postgresql.ENUM(
    "main",
    "blog",
    "docs",
    "store",
    "support",
    "social",
    "marketplace",
    "other",
    name="domain_type",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitor_domains",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column(
            "domain_type",
            domain_type_enum,
            server_default="main",
            nullable=False,
        ),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_competitor_domains_competitor_domain",
        "competitor_domains",
        ["competitor_id", "domain"],
        unique=True,
    )
    op.create_index(
        "ix_competitor_domains_competitor_id",
        "competitor_domains",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        "ix_competitor_domains_domain", "competitor_domains", ["domain"], unique=False
    )
    op.create_index(
        "ix_competitor_domains_organization_id",
        "competitor_domains",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_competitor_domains_project_id",
        "competitor_domains",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitor_domains_project_id", table_name="competitor_domains")
    op.drop_index(
        "ix_competitor_domains_organization_id", table_name="competitor_domains"
    )
    op.drop_index("ix_competitor_domains_domain", table_name="competitor_domains")
    op.drop_index(
        "ix_competitor_domains_competitor_id", table_name="competitor_domains"
    )
    op.drop_index(
        "ix_competitor_domains_competitor_domain", table_name="competitor_domains"
    )
    op.drop_table("competitor_domains")
    # ### end Alembic commands ###
