"""create_ai_observations_table

Revision ID: 21121e97de7b
Revises: a70cbe40597d
Create Date: 2026-06-27 19:23:19.747720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21121e97de7b"
down_revision: Union[str, Sequence[str], None] = "a70cbe40597d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_batch_id", sa.UUID(), nullable=False),
        sa.Column("prompt_run_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("response_markdown", sa.Text(), nullable=True),
        sa.Column("response_html", sa.Text(), nullable=True),
        sa.Column("answer_title", sa.Text(), nullable=True),
        sa.Column("answer_url", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column(
            "citations_raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "search_queries_raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "shopping_cards_raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "followups_raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("screenshot_path", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "is_empty", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["prompt_run_id"], ["prompt_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_observations_content_hash",
        "ai_observations",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_ai_observations_observed_at",
        "ai_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_observations_organization_id",
        "ai_observations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_ai_observations_platform_id",
        "ai_observations",
        ["platform_id"],
        unique=False,
    )
    op.create_index(
        "ix_ai_observations_project_id", "ai_observations", ["project_id"], unique=False
    )
    op.create_index(
        "ix_ai_observations_prompt_id", "ai_observations", ["prompt_id"], unique=False
    )
    op.create_index(
        "ix_ai_observations_prompt_run_content_hash",
        "ai_observations",
        ["prompt_run_id", "content_hash"],
        unique=True,
    )
    op.create_index(
        "ix_ai_observations_prompt_run_id",
        "ai_observations",
        ["prompt_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_ai_observations_run_batch_id",
        "ai_observations",
        ["run_batch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_observations_run_batch_id", table_name="ai_observations")
    op.drop_index("ix_ai_observations_prompt_run_id", table_name="ai_observations")
    op.drop_index(
        "ix_ai_observations_prompt_run_content_hash", table_name="ai_observations"
    )
    op.drop_index("ix_ai_observations_prompt_id", table_name="ai_observations")
    op.drop_index("ix_ai_observations_project_id", table_name="ai_observations")
    op.drop_index("ix_ai_observations_platform_id", table_name="ai_observations")
    op.drop_index("ix_ai_observations_organization_id", table_name="ai_observations")
    op.drop_index("ix_ai_observations_observed_at", table_name="ai_observations")
    op.drop_index("ix_ai_observations_content_hash", table_name="ai_observations")
    op.drop_table("ai_observations")
    # ### end Alembic commands ###
