"""create_rankings_table

Revision ID: 2e7f164cdbfd
Revises: 26c7dd039721
Create Date: 2026-06-27 19:49:05.650295

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2e7f164cdbfd"
down_revision: Union[str, Sequence[str], None] = "26c7dd039721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ranking_entity_type_enum = postgresql.ENUM(
    "brand",
    "competitor",
    "other",
    name="ranking_entity_type",
    create_type=False,
)

ranking_basis_enum = postgresql.ENUM(
    "explicit_numbered_list",
    "order_of_mention",
    "recommendation_order",
    "inferred",
    name="ranking_basis",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rankings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_batch_id", sa.UUID(), nullable=False),
        sa.Column("prompt_run_id", sa.UUID(), nullable=False),
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("extraction_result_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("competitor_id", sa.UUID(), nullable=True),
        sa.Column(
            "entity_type",
            ranking_entity_type_enum,
            nullable=False,
        ),
        sa.Column("entity_name", sa.Text(), nullable=False),
        sa.Column("rank_position", sa.Integer(), nullable=False),
        sa.Column(
            "ranking_basis",
            ranking_basis_enum,
            nullable=False,
        ),
        sa.Column("ranking_context", sa.Text(), nullable=True),
        sa.Column(
            "is_recommended",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "confidence_score",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["extraction_result_id"], ["extraction_results.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"], ["ai_observations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["prompt_run_id"], ["prompt_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rankings_competitor_id", "rankings", ["competitor_id"], unique=False
    )
    op.create_index(
        "ix_rankings_entity_type", "rankings", ["entity_type"], unique=False
    )
    op.create_index(
        "ix_rankings_extraction_result_id",
        "rankings",
        ["extraction_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_rankings_is_recommended", "rankings", ["is_recommended"], unique=False
    )
    op.create_index(
        "ix_rankings_observation_id", "rankings", ["observation_id"], unique=False
    )
    op.create_index(
        "ix_rankings_organization_id", "rankings", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_rankings_platform_id", "rankings", ["platform_id"], unique=False
    )
    op.create_index("ix_rankings_project_id", "rankings", ["project_id"], unique=False)
    op.create_index("ix_rankings_prompt_id", "rankings", ["prompt_id"], unique=False)
    op.create_index(
        "ix_rankings_prompt_run_id", "rankings", ["prompt_run_id"], unique=False
    )
    op.create_index(
        "ix_rankings_rank_position", "rankings", ["rank_position"], unique=False
    )
    op.create_index(
        "ix_rankings_run_batch_id", "rankings", ["run_batch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rankings_run_batch_id", table_name="rankings")
    op.drop_index("ix_rankings_rank_position", table_name="rankings")
    op.drop_index("ix_rankings_prompt_run_id", table_name="rankings")
    op.drop_index("ix_rankings_prompt_id", table_name="rankings")
    op.drop_index("ix_rankings_project_id", table_name="rankings")
    op.drop_index("ix_rankings_platform_id", table_name="rankings")
    op.drop_index("ix_rankings_organization_id", table_name="rankings")
    op.drop_index("ix_rankings_observation_id", table_name="rankings")
    op.drop_index("ix_rankings_is_recommended", table_name="rankings")
    op.drop_index("ix_rankings_extraction_result_id", table_name="rankings")
    op.drop_index("ix_rankings_entity_type", table_name="rankings")
    op.drop_index("ix_rankings_competitor_id", table_name="rankings")
    op.drop_table("rankings")
    # ### end Alembic commands ###
