"""create_citation_gaps_table

Revision ID: 49f869f2928c
Revises: 7dd5225b452b
Create Date: 2026-06-27 19:58:55.024902

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "49f869f2928c"
down_revision: Union[str, Sequence[str], None] = "7dd5225b452b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

citation_gap_type_enum = postgresql.ENUM(
    "brand_mentioned_not_cited",
    "competitor_cited_brand_not_cited",
    "third_party_dominates",
    "owned_content_missing",
    "weak_owned_page",
    name="citation_gap_type",
    create_type=False,
)

citation_gap_severity_enum = postgresql.ENUM(
    "low",
    "medium",
    "high",
    "critical",
    name="citation_gap_severity",
    create_type=False,
)

citation_gap_status_enum = postgresql.ENUM(
    "open",
    "reviewed",
    "fixed",
    "ignored",
    "archived",
    name="citation_gap_status",
    create_type=False,
)
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citation_gaps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=True),
        sa.Column("prompt_set_id", sa.UUID(), nullable=True),
        sa.Column("run_batch_id", sa.UUID(), nullable=True),
        sa.Column("platform_id", sa.UUID(), nullable=True),
        sa.Column("competitor_id", sa.UUID(), nullable=True),
        sa.Column("evidence_observation_id", sa.UUID(), nullable=True),
        sa.Column("evidence_citation_id", sa.UUID(), nullable=True),
        sa.Column(
            "gap_type",
            citation_gap_type_enum,
            nullable=False,
        ),
        sa.Column(
            "severity",
            citation_gap_severity_enum,
            server_default="medium",
            nullable=False,
        ),
        sa.Column("source_domain", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "evidence_count", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "owned_domain_present",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "competitor_present",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "brand_mentioned",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "brand_recommended",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.Column(
            "status",
            citation_gap_status_enum,
            server_default="open",
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"], ["competitors.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_citation_id"], ["citations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_observation_id"], ["ai_observations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["prompt_set_id"], ["prompt_sets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_citation_gaps_competitor_id",
        "citation_gaps",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_evidence_citation_id",
        "citation_gaps",
        ["evidence_citation_id"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_evidence_observation_id",
        "citation_gaps",
        ["evidence_observation_id"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_first_seen_at",
        "citation_gaps",
        ["first_seen_at"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_gap_type", "citation_gaps", ["gap_type"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_last_seen_at", "citation_gaps", ["last_seen_at"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_organization_id",
        "citation_gaps",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_platform_id", "citation_gaps", ["platform_id"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_project_id", "citation_gaps", ["project_id"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_prompt_id", "citation_gaps", ["prompt_id"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_prompt_set_id",
        "citation_gaps",
        ["prompt_set_id"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_run_batch_id", "citation_gaps", ["run_batch_id"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_severity", "citation_gaps", ["severity"], unique=False
    )
    op.create_index(
        "ix_citation_gaps_source_domain",
        "citation_gaps",
        ["source_domain"],
        unique=False,
    )
    op.create_index(
        "ix_citation_gaps_status", "citation_gaps", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_citation_gaps_status", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_source_domain", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_severity", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_run_batch_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_prompt_set_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_prompt_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_project_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_platform_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_organization_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_last_seen_at", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_gap_type", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_first_seen_at", table_name="citation_gaps")
    op.drop_index(
        "ix_citation_gaps_evidence_observation_id", table_name="citation_gaps"
    )
    op.drop_index("ix_citation_gaps_evidence_citation_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_competitor_id", table_name="citation_gaps")
    op.drop_table("citation_gaps")
    # ### end Alembic commands ###
