"""create_competitors_table

Revision ID: 534fb82c744e
Revises: e78e788a9f91
Create Date: 2026-06-27 17:54:35.501727

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "534fb82c744e"
down_revision: Union[str, Sequence[str], None] = "e78e788a9f91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

competitors_status_enum = postgresql.ENUM(
    "active", "ignored", "archived", name="competitor_status", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("canonical_domain", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("market", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            competitors_status_enum,
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_competitors_canonical_domain",
        "competitors",
        ["canonical_domain"],
        unique=False,
    )
    op.create_index("ix_competitors_name", "competitors", ["name"], unique=False)
    op.create_index(
        "ix_competitors_organization_id",
        "competitors",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_competitors_project_id", "competitors", ["project_id"], unique=False
    )
    op.create_index(
        "ix_competitors_project_name",
        "competitors",
        ["project_id", "name"],
        unique=False,
    )
    op.create_index("ix_competitors_status", "competitors", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitors_status", table_name="competitors")
    op.drop_index("ix_competitors_project_name", table_name="competitors")
    op.drop_index("ix_competitors_project_id", table_name="competitors")
    op.drop_index("ix_competitors_organization_id", table_name="competitors")
    op.drop_index("ix_competitors_name", table_name="competitors")
    op.drop_index("ix_competitors_canonical_domain", table_name="competitors")
    op.drop_table("competitors")
    # ### end Alembic commands ###
