"""create_organization_memberships_table

Revision ID: 68e70e8b8edf
Revises: 2aa2fb276293
Create Date: 2026-06-27 10:41:56.817570

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "68e70e8b8edf"
down_revision: Union[str, Sequence[str], None] = "2aa2fb276293"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

membership_role_enum = postgresql.ENUM(
    "owner",
    "admin",
    "member",
    "viewer",
    name="membership_role",
    create_type=False
)

membership_status_enum = postgresql.ENUM(
    "active",
    "invited",
    "removed",
    name="membership_status",
    create_type=False
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            membership_role_enum,
            server_default="member",
            nullable=False,
        ),
        sa.Column(
            "status",
            membership_status_enum,
            server_default="active",
            nullable=False,
        ),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_organization_memberships_org_user",
        "organization_memberships",
        ["organization_id", "user_id"],
        unique=True,
    )
    op.create_index(
        "ix_organization_memberships_organization_id",
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_organization_memberships_role",
        "organization_memberships",
        ["role"],
        unique=False,
    )
    op.create_index(
        "ix_organization_memberships_status",
        "organization_memberships",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_organization_memberships_user_id",
        "organization_memberships",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_organization_memberships_user_id", table_name="organization_memberships"
    )
    op.drop_index(
        "ix_organization_memberships_status", table_name="organization_memberships"
    )
    op.drop_index(
        "ix_organization_memberships_role", table_name="organization_memberships"
    )
    op.drop_index(
        "ix_organization_memberships_organization_id",
        table_name="organization_memberships",
    )
    op.drop_index(
        "ix_organization_memberships_org_user", table_name="organization_memberships"
    )
    op.drop_table("organization_memberships")
    # ### end Alembic commands ###
