"""create_metric_snapshots_table

Revision ID: 7dd5225b452b
Revises: 2e7f164cdbfd
Create Date: 2026-06-27 19:54:15.066927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7dd5225b452b"
down_revision: Union[str, Sequence[str], None] = "2e7f164cdbfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

metric_snapshot_type_enum = postgresql.ENUM(
    "batch",
    "daily",
    "weekly",
    "monthly",
    "manual_report",
    name="metric_snapshot_type",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("prompt_set_id", sa.UUID(), nullable=True),
        sa.Column("run_batch_id", sa.UUID(), nullable=True),
        sa.Column("platform_id", sa.UUID(), nullable=True),
        sa.Column(
            "snapshot_type",
            metric_snapshot_type_enum,
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "total_prompt_runs",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "successful_prompt_runs",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "failed_prompt_runs",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "total_observations",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "brand_mention_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "brand_mention_rate",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "brand_citation_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "brand_citation_rate",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "brand_recommendation_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "brand_recommendation_rate",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("avg_brand_rank", sa.Numeric(), nullable=True),
        sa.Column("median_brand_rank", sa.Numeric(), nullable=True),
        sa.Column(
            "competitor_mention_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "competitor_recommendation_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "owned_citation_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "competitor_citation_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "third_party_citation_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "visibility_score",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "citation_score", sa.Numeric(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "recommendation_score",
            sa.Numeric(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "ranking_score", sa.Numeric(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("sentiment_score", sa.Numeric(), nullable=True),
        sa.Column("volatility_score", sa.Numeric(), nullable=True),
        sa.Column("methodology_version", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_set_id"], ["prompt_sets.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_snapshots_generated_at",
        "metric_snapshots",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_methodology_version",
        "metric_snapshots",
        ["methodology_version"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_organization_id",
        "metric_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_platform_id",
        "metric_snapshots",
        ["platform_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_project_id",
        "metric_snapshots",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_prompt_set_id",
        "metric_snapshots",
        ["prompt_set_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_run_batch_id",
        "metric_snapshots",
        ["run_batch_id"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_snapshot_type",
        "metric_snapshots",
        ["snapshot_type"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_window_end",
        "metric_snapshots",
        ["window_end"],
        unique=False,
    )
    op.create_index(
        "ix_metric_snapshots_window_start",
        "metric_snapshots",
        ["window_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_metric_snapshots_window_start", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_window_end", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_snapshot_type", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_run_batch_id", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_prompt_set_id", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_project_id", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_platform_id", table_name="metric_snapshots")
    op.drop_index("ix_metric_snapshots_organization_id", table_name="metric_snapshots")
    op.drop_index(
        "ix_metric_snapshots_methodology_version", table_name="metric_snapshots"
    )
    op.drop_index("ix_metric_snapshots_generated_at", table_name="metric_snapshots")
    op.drop_table("metric_snapshots")
    # ### end Alembic commands ###
