"""create_ai_platforms_table

Revision ID: 8ee39648f473
Revises: c7b074701130
Create Date: 2026-06-27 19:01:50.084443

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ee39648f473"
down_revision: Union[str, Sequence[str], None] = "c7b074701130"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ai_provider_type_enum = postgresql.ENUM(
    "ui_scrape",
    "api",
    "third_party_api",
    "manual_import",
    name="ai_provider_type",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_platforms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "provider_type",
            ai_provider_type_enum,
            nullable=False,
        ),
        sa.Column(
            "supports_citations",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "supports_search_queries",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "supports_shopping_cards",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_platforms_code", "ai_platforms", ["code"], unique=True)
    op.create_index(
        "ix_ai_platforms_is_active", "ai_platforms", ["is_active"], unique=False
    )
    op.create_index(
        "ix_ai_platforms_provider_type", "ai_platforms", ["provider_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_platforms_provider_type", table_name="ai_platforms")
    op.drop_index("ix_ai_platforms_is_active", table_name="ai_platforms")
    op.drop_index("ix_ai_platforms_code", table_name="ai_platforms")
    op.drop_table("ai_platforms")
    # ### end Alembic commands ###
