"""create_prompt_runs_table

Revision ID: a70cbe40597d
Revises: c062547740fa
Create Date: 2026-06-27 19:15:17.513210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a70cbe40597d"
down_revision: Union[str, Sequence[str], None] = "c062547740fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

prompt_run_status_enum = postgresql.ENUM(
    "pending",
    "running",
    "succeeded",
    "failed",
    "timeout",
    "blocked",
    "cancelled",
    name="prompt_run_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_batch_id", sa.UUID(), nullable=False),
        sa.Column("prompt_set_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column(
            "run_number", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "status",
            prompt_run_status_enum,
            server_default="pending",
            nullable=False,
        ),
        sa.Column("prompt_text_snapshot", sa.Text(), nullable=False),
        sa.Column("prompt_hash_snapshot", sa.Text(), nullable=False),
        sa.Column("provider_name", sa.Text(), nullable=True),
        sa.Column("model_name", sa.Text(), nullable=True),
        sa.Column("locale", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("device_type", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "raw_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["prompt_set_id"], ["prompt_sets.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["run_batch_id"], ["run_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_prompt_runs_batch_prompt_run_number",
        "prompt_runs",
        ["run_batch_id", "prompt_id", "run_number"],
        unique=True,
    )
    op.create_index(
        "ix_prompt_runs_completed_at", "prompt_runs", ["completed_at"], unique=False
    )
    op.create_index(
        "ix_prompt_runs_organization_id",
        "prompt_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_runs_platform_id", "prompt_runs", ["platform_id"], unique=False
    )
    op.create_index(
        "ix_prompt_runs_project_id", "prompt_runs", ["project_id"], unique=False
    )
    op.create_index(
        "ix_prompt_runs_prompt_id", "prompt_runs", ["prompt_id"], unique=False
    )
    op.create_index(
        "ix_prompt_runs_prompt_set_id", "prompt_runs", ["prompt_set_id"], unique=False
    )
    op.create_index(
        "ix_prompt_runs_run_batch_id", "prompt_runs", ["run_batch_id"], unique=False
    )
    op.create_index(
        "ix_prompt_runs_run_number", "prompt_runs", ["run_number"], unique=False
    )
    op.create_index("ix_prompt_runs_status", "prompt_runs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompt_runs_status", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_run_number", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_run_batch_id", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_prompt_set_id", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_prompt_id", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_project_id", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_platform_id", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_organization_id", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_completed_at", table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_batch_prompt_run_number", table_name="prompt_runs")
    op.drop_table("prompt_runs")
    # ### end Alembic commands ###
