"""create_run_batches_table

Revision ID: c062547740fa
Revises: 8ee39648f473
Create Date: 2026-06-27 19:08:03.420735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c062547740fa"
down_revision: Union[str, Sequence[str], None] = "8ee39648f473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

run_batch_type_enum = postgresql.ENUM(
    "manual",
    "scheduled",
    "backfill",
    "test",
    name="run_batch_type",
    create_type=False,
)

run_batch_status_enum = postgresql.ENUM(
    "pending",
    "running",
    "completed",
    "failed",
    "cancelled",
    "partial",
    name="run_batch_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("prompt_set_id", sa.UUID(), nullable=False),
        sa.Column("platform_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "run_type",
            run_batch_type_enum,
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "status",
            run_batch_status_enum,
            nullable=False,
        ),
        sa.Column(
            "repeats_per_prompt",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"], ["ai_platforms.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_set_id"], ["prompt_sets.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_run_batches_completed_at", "run_batches", ["completed_at"], unique=False
    )
    op.create_index(
        "ix_run_batches_created_by_user_id",
        "run_batches",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_run_batches_organization_id",
        "run_batches",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_run_batches_platform_id", "run_batches", ["platform_id"], unique=False
    )
    op.create_index(
        "ix_run_batches_project_id", "run_batches", ["project_id"], unique=False
    )
    op.create_index(
        "ix_run_batches_prompt_set_id", "run_batches", ["prompt_set_id"], unique=False
    )
    op.create_index(
        "ix_run_batches_scheduled_at", "run_batches", ["scheduled_at"], unique=False
    )
    op.create_index(
        "ix_run_batches_started_at", "run_batches", ["started_at"], unique=False
    )
    op.create_index("ix_run_batches_status", "run_batches", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_batches_status", table_name="run_batches")
    op.drop_index("ix_run_batches_started_at", table_name="run_batches")
    op.drop_index("ix_run_batches_scheduled_at", table_name="run_batches")
    op.drop_index("ix_run_batches_prompt_set_id", table_name="run_batches")
    op.drop_index("ix_run_batches_project_id", table_name="run_batches")
    op.drop_index("ix_run_batches_platform_id", table_name="run_batches")
    op.drop_index("ix_run_batches_organization_id", table_name="run_batches")
    op.drop_index("ix_run_batches_created_by_user_id", table_name="run_batches")
    op.drop_index("ix_run_batches_completed_at", table_name="run_batches")
    op.drop_table("run_batches")
    # ### end Alembic commands ###
