"""create_prompt_set_prompts_table

Revision ID: c7b074701130
Revises: fd862e4042bb
Create Date: 2026-06-27 18:58:08.884037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c7b074701130"
down_revision: Union[str, Sequence[str], None] = "fd862e4042bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_set_prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("prompt_set_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column(
            "position", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("weight", sa.Numeric(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prompt_set_id"], ["prompt_sets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_prompt_set_prompts_organization_id",
        "prompt_set_prompts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_set_prompts_project_id",
        "prompt_set_prompts",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_set_prompts_prompt_id",
        "prompt_set_prompts",
        ["prompt_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_set_prompts_prompt_set_id",
        "prompt_set_prompts",
        ["prompt_set_id"],
        unique=False,
    )
    op.create_index(
        "ix_prompt_set_prompts_set_prompt",
        "prompt_set_prompts",
        ["prompt_set_id", "prompt_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompt_set_prompts_set_prompt", table_name="prompt_set_prompts")
    op.drop_index(
        "ix_prompt_set_prompts_prompt_set_id", table_name="prompt_set_prompts"
    )
    op.drop_index("ix_prompt_set_prompts_prompt_id", table_name="prompt_set_prompts")
    op.drop_index("ix_prompt_set_prompts_project_id", table_name="prompt_set_prompts")
    op.drop_index(
        "ix_prompt_set_prompts_organization_id", table_name="prompt_set_prompts"
    )
    op.drop_table("prompt_set_prompts")
    # ### end Alembic commands ###
