"""create_project_domains_table

Revision ID: e78e788a9f91
Revises: 61394d6db3b9
Create Date: 2026-06-27 17:45:57.068232

"""

from typing import Sequence, Union


from sqlalchemy.dialects import postgresql


from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision: str = "e78e788a9f91"

down_revision: Union[str, Sequence[str], None] = "61394d6db3b9"

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


domain_type_enum = postgresql.ENUM(
    "main",
    "blog",
    "docs",
    "store",
    "support",
    "social",
    "marketplace",
    "other",
    name="domain_type",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "project_domains",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column(
            "domain_type",
            domain_type_enum,
            server_default="main",
            nullable=False,
        ),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_project_domains_domain", "project_domains", ["domain"], unique=False
    )

    op.create_index(
        "ix_project_domains_organization_id",
        "project_domains",
        ["organization_id"],
        unique=False,
    )

    op.create_index(
        "ix_project_domains_project_domain",
        "project_domains",
        ["project_id", "domain"],
        unique=True,
    )

    op.create_index(
        "ix_project_domains_project_id", "project_domains", ["project_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("ix_project_domains_project_id", table_name="project_domains")

    op.drop_index("ix_project_domains_project_domain", table_name="project_domains")

    op.drop_index("ix_project_domains_organization_id", table_name="project_domains")

    op.drop_index("ix_project_domains_domain", table_name="project_domains")

    op.drop_table("project_domains")

    # ### end Alembic commands ###
