"""create_brand_projects_table

Revision ID: f852f7358045
Revises: 68e70e8b8edf
Create Date: 2026-06-27 11:35:14.922935

"""
from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f852f7358045'
down_revision: Union[str, Sequence[str], None] = '68e70e8b8edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

projects_status_enum = postgresql.ENUM(
    "active",
    "paused",
    "archived",
    name="brand_project_status",
    create_type=False
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=False),
    sa.Column('canonical_domain', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', projects_status_enum, server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brand_projects_brand_name', 'brand_projects', ['brand_name'], unique=False)
    op.create_index('ix_brand_projects_canonical_domain', 'brand_projects', ['canonical_domain'], unique=False)
    op.create_index('ix_brand_projects_created_by_user_id', 'brand_projects', ['created_by_user_id'], unique=False)
    op.create_index('ix_brand_projects_org_name', 'brand_projects', ['organization_id', 'name'], unique=False)
    op.create_index('ix_brand_projects_organization_id', 'brand_projects', ['organization_id'], unique=False)
    op.create_index('ix_brand_projects_status', 'brand_projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brand_projects_status', table_name='brand_projects')
    op.drop_index('ix_brand_projects_organization_id', table_name='brand_projects')
    op.drop_index('ix_brand_projects_org_name', table_name='brand_projects')
    op.drop_index('ix_brand_projects_created_by_user_id', table_name='brand_projects')
    op.drop_index('ix_brand_projects_canonical_domain', table_name='brand_projects')
    op.drop_index('ix_brand_projects_brand_name', table_name='brand_projects')
    op.drop_table('brand_projects')
    # ### end Alembic commands ###
