"""create_prompts_table

Revision ID: fd862e4042bb
Revises: f453c915f215
Create Date: 2026-06-27 18:36:22.539718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fd862e4042bb"
down_revision: Union[str, Sequence[str], None] = "f453c915f215"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

prompt_intent_type_enum = postgresql.ENUM(
    "best_product",
    "comparison",
    "review",
    "recommendation",
    "problem_solution",
    "brand_check",
    "informational",
    "transactional",
    "local_search",
    name="prompt_intent_type",
    create_type=False,
)

prompt_buyer_stage_enum = postgresql.ENUM(
    "awareness",
    "consideration",
    "purchase",
    "post_purchase",
    name="prompt_buyer_stage",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("prompt_hash", sa.Text(), nullable=False),
        sa.Column("language_code", sa.Text(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column(
            "intent_type",
            prompt_intent_type_enum,
            nullable=False,
        ),
        sa.Column(
            "buyer_stage",
            prompt_buyer_stage_enum,
            nullable=True,
        ),
        sa.Column("persona", sa.Text(), nullable=True),
        sa.Column("expected_brand", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "prompt_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["brand_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prompts_buyer_stage", "prompts", ["buyer_stage"], unique=False)
    op.create_index(
        "ix_prompts_created_by_user_id", "prompts", ["created_by_user_id"], unique=False
    )
    op.create_index("ix_prompts_intent_type", "prompts", ["intent_type"], unique=False)
    op.create_index("ix_prompts_is_active", "prompts", ["is_active"], unique=False)
    op.create_index(
        "ix_prompts_organization_id", "prompts", ["organization_id"], unique=False
    )
    op.create_index("ix_prompts_project_id", "prompts", ["project_id"], unique=False)
    op.create_index(
        "ix_prompts_project_prompt_hash",
        "prompts",
        ["project_id", "prompt_hash"],
        unique=True,
    )
    op.create_index("ix_prompts_prompt_hash", "prompts", ["prompt_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompts_prompt_hash", table_name="prompts")
    op.drop_index("ix_prompts_project_prompt_hash", table_name="prompts")
    op.drop_index("ix_prompts_project_id", table_name="prompts")
    op.drop_index("ix_prompts_organization_id", table_name="prompts")
    op.drop_index("ix_prompts_is_active", table_name="prompts")
    op.drop_index("ix_prompts_intent_type", table_name="prompts")
    op.drop_index("ix_prompts_created_by_user_id", table_name="prompts")
    op.drop_index("ix_prompts_buyer_stage", table_name="prompts")
    op.drop_table("prompts")
    # ### end Alembic commands ###
